--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "PUBLIC"."ASSESSMENT" DROP CONSTRAINT "ASSESSMENT_ID_ALUNO";

ALTER TABLE "PUBLIC"."FREQUENCIA" DROP CONSTRAINT "FREQUENCIA_ID_ALUNO";

ALTER TABLE "PUBLIC"."ALUNO" DROP CONSTRAINT "ALUNO_ID_DIARIO";

ALTER TABLE "PUBLIC"."DIARIO" DROP CONSTRAINT "SYS_PK_49";

ALTER TABLE "PUBLIC"."ASSESSMENT" DROP CONSTRAINT "SYS_PK_59";

ALTER TABLE "PUBLIC"."ALUNO" DROP CONSTRAINT "SYS_REF_ASSESSMENT_ID_ALUNO_61";

ALTER TABLE "PUBLIC"."FREQUENCIA" DROP CONSTRAINT "SYS_PK_55";

ALTER TABLE "PUBLIC"."DIARIO" DROP CONSTRAINT "SYS_REF_ALUNO_ID_DIARIO_53";

ALTER TABLE "PUBLIC"."ALUNO" DROP CONSTRAINT "SYS_REF_FREQUENCIA_ID_ALUNO_57";

ALTER TABLE "PUBLIC"."LOGIN" DROP CONSTRAINT "SYS_PK_47";

ALTER TABLE "PUBLIC"."ALUNO" DROP CONSTRAINT "SYS_PK_51";

DROP INDEX "PUBLIC"."SYS_IDX_46";

DROP INDEX "PUBLIC"."SYS_IDX_50";

DROP INDEX "PUBLIC"."SYS_IDX_48";

DROP INDEX "PUBLIC"."SYS_IDX_54";

DROP INDEX "PUBLIC"."SYS_IDX_52";

DROP INDEX "PUBLIC"."SYS_IDX_58";

DROP INDEX "PUBLIC"."SYS_IDX_56";

DROP INDEX "PUBLIC"."SYS_IDX_60";

DROP TABLE "PUBLIC"."LOGIN";

DROP TABLE "PUBLIC"."FREQUENCIA";

DROP TABLE "PUBLIC"."DIARIO";

DROP TABLE "PUBLIC"."ASSESSMENT";

DROP TABLE "PUBLIC"."ALUNO";

CREATE TABLE "PUBLIC"."LOGIN" (
		"COD_LOGIN" INTEGER NOT NULL,
		"NOM_LOGIN" VARCHAR(30),
		"PASS_LOGIN" VARCHAR(30),
		"NOM_PROFESSOR" VARCHAR(50)
	);

CREATE TABLE "PUBLIC"."FREQUENCIA" (
		"COD_FREQUENCIA" INTEGER NOT NULL,
		"ALUNO_ID" INTEGER NOT NULL,
		"DATA_FREQUENCIA" DATE,
		"FLG_FREQUENCIA" VARCHAR(1)
	);

CREATE TABLE "PUBLIC"."DIARIO" (
		"COD_DIARIO" INTEGER NOT NULL,
		"CURSO" VARCHAR(30) NOT NULL,
		"TURNO" VARCHAR(20) NOT NULL,
		"SERIE" VARCHAR(5) NOT NULL,
		"TURMA" VARCHAR(30) NOT NULL,
		"DISCIPLINA" VARCHAR(30) NOT NULL,
		"PROFESSOR" VARCHAR(30),
		"GEREI" VARCHAR(30),
		"MUNICIPIO" VARCHAR(30),
		"UNID_ESCOLAR" VARCHAR(20)
	);

CREATE TABLE "PUBLIC"."ASSESSMENT" (
		"COD_ASSESSMENT" INTEGER NOT NULL,
		"ALUNO_ID" INTEGER NOT NULL,
		"TIP_ASSESSMENT" VARCHAR(1) NOT NULL,
		"NUM_TIP_ASSESSMENT" INTEGER NOT NULL,
		"NUM_BIMESTRE" INTEGER NOT NULL,
		"DES_ASSESSMENT" VARCHAR(80),
		"DES_OBSERVACAO" VARCHAR(255),
		"DAT_ASSESSMENT" DATE NOT NULL,
		"NOTA_ASSESSMENT" DECIMAL(2 , 2) NOT NULL
	);

CREATE TABLE "PUBLIC"."ALUNO" (
		"COD_ALUNO" INTEGER NOT NULL,
		"DIARIO_ID" INTEGER NOT NULL,
		"NOME" VARCHAR(50) NOT NULL,
		"MATRICULA" INTEGER NOT NULL,
		"FLG_APROVADO" VARCHAR(1),
		"MEDIA_FINAL" DECIMAL(2 , 2) NOT NULL,
		"NOTA_RECUPERACAO" DECIMAL(2 , 2)
	);

CREATE UNIQUE INDEX "PUBLIC"."SYS_IDX_46" ON "PUBLIC"."LOGIN" ("COD_LOGIN" ASC);

CREATE UNIQUE INDEX "PUBLIC"."SYS_IDX_50" ON "PUBLIC"."ALUNO" ("COD_ALUNO" ASC);

CREATE UNIQUE INDEX "PUBLIC"."SYS_IDX_48" ON "PUBLIC"."DIARIO" ("COD_DIARIO" ASC);

CREATE UNIQUE INDEX "PUBLIC"."SYS_IDX_54" ON "PUBLIC"."FREQUENCIA" ("COD_FREQUENCIA" ASC);

CREATE INDEX "PUBLIC"."SYS_IDX_52" ON "PUBLIC"."ALUNO" ("DIARIO_ID" ASC);

CREATE UNIQUE INDEX "PUBLIC"."SYS_IDX_58" ON "PUBLIC"."ASSESSMENT" ("COD_ASSESSMENT" ASC);

CREATE INDEX "PUBLIC"."SYS_IDX_56" ON "PUBLIC"."FREQUENCIA" ("ALUNO_ID" ASC);

CREATE INDEX "PUBLIC"."SYS_IDX_60" ON "PUBLIC"."ASSESSMENT" ("ALUNO_ID" ASC);

ALTER TABLE "PUBLIC"."DIARIO" ADD CONSTRAINT "SYS_PK_49" PRIMARY KEY ("COD_DIARIO");

ALTER TABLE "PUBLIC"."ASSESSMENT" ADD CONSTRAINT "SYS_PK_59" PRIMARY KEY ("COD_ASSESSMENT");

ALTER TABLE "PUBLIC"."ALUNO" ADD CONSTRAINT "SYS_REF_ASSESSMENT_ID_ALUNO_61" UNIQUE ("COD_ALUNO");

ALTER TABLE "PUBLIC"."FREQUENCIA" ADD CONSTRAINT "SYS_PK_55" PRIMARY KEY ("COD_FREQUENCIA");

ALTER TABLE "PUBLIC"."DIARIO" ADD CONSTRAINT "SYS_REF_ALUNO_ID_DIARIO_53" UNIQUE ("COD_DIARIO");

ALTER TABLE "PUBLIC"."ALUNO" ADD CONSTRAINT "SYS_REF_FREQUENCIA_ID_ALUNO_57" UNIQUE ("COD_ALUNO");

ALTER TABLE "PUBLIC"."LOGIN" ADD CONSTRAINT "SYS_PK_47" PRIMARY KEY ("COD_LOGIN");

ALTER TABLE "PUBLIC"."ALUNO" ADD CONSTRAINT "SYS_PK_51" PRIMARY KEY ("COD_ALUNO");

ALTER TABLE "PUBLIC"."ASSESSMENT" ADD CONSTRAINT "ASSESSMENT_ID_ALUNO" FOREIGN KEY ("ALUNO_ID")
	REFERENCES "PUBLIC"."ALUNO" ("COD_ALUNO");

ALTER TABLE "PUBLIC"."FREQUENCIA" ADD CONSTRAINT "FREQUENCIA_ID_ALUNO" FOREIGN KEY ("ALUNO_ID")
	REFERENCES "PUBLIC"."ALUNO" ("COD_ALUNO");

ALTER TABLE "PUBLIC"."ALUNO" ADD CONSTRAINT "ALUNO_ID_DIARIO" FOREIGN KEY ("DIARIO_ID")
	REFERENCES "PUBLIC"."DIARIO" ("COD_DIARIO");

