SELECT * FROM ASSESSMENT ORDER BY 2,3,4,5;

SELECT NUM_BIMESTRE, MAX(NUM_TIP_ASSESSMENT) AS QTD FROM ASSESSMENT GROUP BY NUM_BIMESTRE,TIP_ASSESSMENT;

SELECT * FROM ALUNO;

SELECT * FROM ASSESSMENT WHERE ALUNO_ID = 4 ORDER BY 3,5,4;

SELECT * FROM ASSESSMENT WHERE ALUNO_ID = 8 ORDER BY 3,5,4;

INSERT INTO ALUNO (DIARIO_ID, NOME, MATRICULA) VALUES (2,'ELAINE MACHADO SILVEIRA',33215);

SELECT COD_ALUNO FROM ALUNO WHERE DIARIO_ID = 2 AND NOME = 'OUTRO' AND MATRICULA = 131313;

SELECT AL.COD_ALUNO, AL.NOME, AV.TIP_ASSESSMENT, AV.NUM_TIP_ASSESSMENT, AV.NUM_BIMESTRE, AL.FLG_APROVADO, AV.DAT_ASSESSMENT, 
AV.NOTA_ASSESSMENT, RP.NOTA_RECUPERACAO, AL.NOTA_RECUPERACAO_FINAL, AV.COD_ASSESSMENT, AL.MEDIA_FINAL
FROM ASSESSMENT AV
RIGHT JOIN ALUNO AL ON AL.COD_ALUNO = AV.ALUNO_ID
LEFT JOIN RECUPERACAO RP ON AV.COD_ASSESSMENT = RP.ASSESSMENT_ID
RIGHT JOIN DIARIO DR ON AL.DIARIO_ID = DR.COD_DIARIO
WHERE DR.COD_DIARIO = 2;

INSERT INTO RECUPERACAO (ASSESSMENT_ID, NOTA_RECUPERACAO) VALUES (2, 2.5);

SELECT * FROM RECUPERACAO;

SELECT MAX(NUM_TIP_ASSESSMENT) AS QTD FROM ASSESSMENT
WHERE NUM_BIMESTRE = 2
AND TIP_ASSESSMENT = 'A';

SELECT COALESCE(COD_ASSESSMENT, 0) FROM ASSESSMENT WHERE TIP_ASSESSMENT = 'A' AND NUM_TIP_ASSESSMENT = 1 AND NUM_BIMESTRE = 1 AND ALUNO_ID = 8;

INSERT INTO RECUPERACAO (ASSESSMENT_ID, NOTA_RECUPERACAO, DES_ASSESSMENT, DES_OBSERVACAO,DAT_ASSESSMENT) VALUES (
	(SELECT COALESCE(COD_ASSESSMENT, 0) FROM ASSESSMENT WHERE TIP_ASSESSMENT = 'R'	AND NUM_TIP_ASSESSMENT = 4 AND NUM_BIMESTRE = 1 AND ALUNO_ID = 4),
	9.0,'lalala','blablabla','2013-06-07')

INSERT INTO ASSESSMENT (TIP_ASSESSMENT, NUM_TIP_ASSESSMENT, NUM_BIMESTRE, DES_ASSESSMENT, DES_OBSERVACAO, DAT_ASSESSMENT, NOTA_ASSESSMENT, ALUNO_ID) VALUES ('T',null,4,'lalala','leklek','2013-06-04',5.5,33);

SELECT AV.COD_ASSESSMENT, AV.ALUNO_ID,AL.NOME,AV.TIP_ASSESSMENT,AV.NUM_TIP_ASSESSMENT,AV.NUM_BIMESTRE,AV.DES_ASSESSMENT,AV.DES_OBSERVACAO,AV.DAT_ASSESSMENT,AV.NOTA_ASSESSMENT
FROM ASSESSMENT AV
	JOIN ALUNO AL ON AL.COD_ALUNO = AV.ALUNO_ID
	JOIN DIARIO DR ON AL.DIARIO_ID = DR.COD_DIARIO
WHERE AV.NUM_BIMESTRE = 1 AND DR.COD_DIARIO = 2;

SELECT MAX(NUM_TIP_ASSESSMENT) AS QTD FROM ASSESSMENT AV
JOIN ALUNO AL ON AL.COD_ALUNO = AV.ALUNO_ID
JOIN DIARIO D ON D.COD_DIARIO = AL.DIARIO_ID
WHERE AV.NUM_BIMESTRE = 2
AND AV.TIP_ASSESSMENT = 'A'
AND D.COD_DIARIO = 2
AND AL.COD_ALUNO = 4;

SELECT R.COD_RECUPERACAO, AV.ALUNO_ID,AL.NOME,AV.TIP_ASSESSMENT,
AV.NUM_TIP_ASSESSMENT,AV.NUM_BIMESTRE,R.DES_ASSESSMENT,
R.DES_OBSERVACAO,R.DAT_ASSESSMENT,R.NOTA_RECUPERACAO 
FROM RECUPERACAO R
JOIN ASSESSMENT AV ON AV.COD_ASSESSMENT = R.ASSESSMENT_ID
JOIN ALUNO AL ON AL.COD_ALUNO = AV.ALUNO_ID
JOIN DIARIO DR ON AL.DIARIO_ID = DR.COD_DIARIO
WHERE AV.NUM_BIMESTRE = 1
AND DR.COD_DIARIO = 1;

SELECT * FROM ALUNO WHERE DIARIO_ID = 3;

SELECT * FROM DIARIO;

DELETE FROM DIARIO WHERE COD_DIARIO = 3;

INSERT INTO "PUBLIC"."DIARIO" (COD_DIARIO,CURSO,TURNO,SERIE,TURMA,DISCIPLINA,PROFESSOR,GEREI,MUNICIPIO,UNID_ESCOLAR) VALUES (3,'teste','teste','teste','teste','teste','ELAINE MACHADO SILVEIRA','teste','teste','teste');

